`timescale 1ns/1ps

module riscv_soc #(
    parameter RAM_ADDR_WIDTH = 12
)(
    input wire clk,
    input wire rst,
    input wire uart_rx
);

    // ============================================================
    // CPU INSTRUCTION BUS
    // ============================================================

    wire [31:0] imem_addr;
    wire [31:0] imem_rdata;


    // ============================================================
    // CPU RAM DATA BUS
    // ============================================================

    wire        dmem_read;
    wire        dmem_write;
    wire [31:0] dmem_addr;
    wire [31:0] dmem_wdata;
    wire [31:0] dmem_rdata;


    // ============================================================
    // CPU EXTERNAL MMIO BUS
    // ============================================================

    wire        mmio_read;
    wire        mmio_write;
    wire [31:0] mmio_addr;
    wire [31:0] mmio_wdata;
    wire [31:0] mmio_rdata;


    // ============================================================
    // UNIFIED CPU BUS
    //
    // The CPU has two external memory-side interfaces:
    //
    //   dmem_*  -> normal RAM access
    //   mmio_*  -> external MMIO access
    //
    // Convert them into one bus going into soc_bus.
    // ============================================================

    wire        cpu_bus_read;
    wire        cpu_bus_write;
    wire [31:0] cpu_bus_addr;
    wire [31:0] cpu_bus_wdata;
    wire [31:0] cpu_bus_rdata;


    assign cpu_bus_read =
        dmem_read |
        mmio_read;

    assign cpu_bus_write =
        dmem_write |
        mmio_write;


    assign cpu_bus_addr =
        (mmio_read || mmio_write)
            ? mmio_addr
            : dmem_addr;


    assign cpu_bus_wdata =
        mmio_write
            ? mmio_wdata
            : dmem_wdata;


    // Return bus data to the CPU.
    //
    // Only the active CPU interface consumes the returned data.

    assign dmem_rdata = cpu_bus_rdata;
    assign mmio_rdata = cpu_bus_rdata;


    // ============================================================
    // UART RX INTERRUPT
    // ============================================================

    wire uart_rx_irq;


    // ============================================================
    // SOC BUS
    // ============================================================

    wire        ram_read;
    wire        ram_write;

    wire [31:0] ram_addr;
    wire [31:0] ram_wdata;
    wire [31:0] ram_rdata;

    wire        bus_mmio_read;
    wire        bus_mmio_write;

    wire [31:0] bus_mmio_addr;
    wire [31:0] bus_mmio_wdata;
    wire [31:0] bus_mmio_rdata;

    wire        ram_sel;
    wire        mmio_sel;


    // ============================================================
    // INSTRUCTION RAM
    // ============================================================

    soc_ram #(
        .ADDR_WIDTH(RAM_ADDR_WIDTH)
    ) imem_ram (
        .clk(clk),

        .read_en(1'b1),
        .read_addr(imem_addr),
        .read_data(imem_rdata),

        .write_en(1'b0),
        .write_addr(32'b0),
        .write_data(32'b0)
    );


    // ============================================================
    // DATA RAM
    // ============================================================

    soc_ram #(
        .ADDR_WIDTH(RAM_ADDR_WIDTH)
    ) dmem_ram (
        .clk(clk),

        .read_en(ram_read),
        .read_addr(ram_addr),
        .read_data(ram_rdata),

        .write_en(ram_write),
        .write_addr(ram_addr),
        .write_data(ram_wdata)
    );


    // ============================================================
    // SOC BUS
    // ============================================================

    soc_bus bus (

        .cpu_read(cpu_bus_read),
        .cpu_write(cpu_bus_write),

        .cpu_addr(cpu_bus_addr),
        .cpu_wdata(cpu_bus_wdata),
        .cpu_rdata(cpu_bus_rdata),


        .ram_read(ram_read),
        .ram_write(ram_write),

        .ram_addr(ram_addr),
        .ram_wdata(ram_wdata),
        .ram_rdata(ram_rdata),


        .mmio_read(bus_mmio_read),
        .mmio_write(bus_mmio_write),

        .mmio_addr(bus_mmio_addr),
        .mmio_wdata(bus_mmio_wdata),
        .mmio_rdata(bus_mmio_rdata),


        .ram_sel(ram_sel),
        .mmio_sel(mmio_sel)
    );


    // ============================================================
    // EXTERNAL MMIO DECODER
    //
    // IMPORTANT:
    //
    // bus_mmio_read/write come FROM soc_bus.
    //
    // mmio_dec_read/write are separate signals generated by the
    // decoder. They must NOT be connected back onto the same
    // bus_mmio_read/write nets.
    // ============================================================

    wire gpio_sel;
    wire uart_tx_sel;
    wire uart_rx_sel;
    wire status_sel;
    wire control_sel;

    wire mmio_dec_read;
    wire mmio_dec_write;


    mmio_decoder mmio (
    .mem_read(bus_mmio_read),
    .mem_write(bus_mmio_write),
    .address(bus_mmio_addr),
    .write_data(bus_mmio_wdata),

    // Decoder does not drive the SoC read-data bus.
    .read_data(),

    .gpio_sel(gpio_sel),
    .uart_tx_sel(uart_tx_sel),
    .uart_rx_sel(uart_rx_sel),

    .mmio_read(mmio_dec_read),
    .mmio_write(mmio_dec_write),

    .status_sel(status_sel),
    .control_sel(control_sel)
);


    // ============================================================
    // GPIO
    // ============================================================

    wire [31:0] gpio_read_data;
    wire [31:0] gpio_out;


    mmio_gpio gpio (

        .clk(clk),
        .rst(rst),

        .write_enable(
            bus_mmio_write &&
            gpio_sel
        ),

        .read_enable(
            bus_mmio_read &&
            gpio_sel
        ),

        .write_data(bus_mmio_wdata),

        .read_data(gpio_read_data),

        .gpio_out(gpio_out)
    );


    // ============================================================
    // UART TX
    // ============================================================

    wire uart_tx;
    wire uart_tx_busy;


    mmio_uart_tx #(
        .CLKS_PER_BIT(4)
    ) uart_tx_peripheral (

        .clk(clk),
        .rst(rst),

        .write_enable(
            bus_mmio_write &&
            uart_tx_sel
        ),

        .write_data(bus_mmio_wdata),

        .tx(uart_tx),
        .busy(uart_tx_busy)
    );


    // ============================================================
    // UART RX
    // ============================================================

    wire [31:0] uart_rx_read_data;

    wire uart_rx_data_valid;
    wire uart_rx_receiving;


    mmio_uart_rx #(
        .CLKS_PER_BIT(4)
    ) uart_rx_peripheral (

        .clk(clk),
        .rst(rst),

        .rx(uart_rx),

        .read_enable(
            bus_mmio_read &&
            uart_rx_sel
        ),

        .read_data(uart_rx_read_data),

        .data_valid(uart_rx_data_valid),

        .receiving_status(uart_rx_receiving)
    );


    // ============================================================
    // STATUS REGISTER
    //
    // STATUS = 
    // bit 0 : UART TX busy
    // bit 1 : UART RX data valid
    // bit 2 : UART RX receiving
    // ============================================================

    wire [31:0] status_read_data;


    assign status_read_data = {

        29'b0,

        uart_rx_receiving,

        uart_rx_data_valid,

        uart_tx_busy

    };


    // ============================================================
    // CONTROL REGISTER
    //
    // bit 0 = UART RX interrupt enable
    // ============================================================

    reg uart_rx_interrupt_enable;


    always @(posedge clk) begin

        if (rst) begin

            uart_rx_interrupt_enable <= 1'b0;

        end

        else if (
            bus_mmio_write &&
            control_sel
        ) begin

            uart_rx_interrupt_enable <=
                bus_mmio_wdata[0];

        end

    end


    // ============================================================
    // UART RX INTERRUPT PENDING LATCH
    // ============================================================

    reg uart_rx_interrupt_pending_latched;

    wire uart_rx_interrupt_clear;


    // Reading UART RX acknowledges/clears the pending interrupt.

    assign uart_rx_interrupt_clear =
        bus_mmio_read &&
        uart_rx_sel;


    always @(posedge clk) begin

        if (rst) begin

            uart_rx_interrupt_pending_latched <=
                1'b0;

        end

        else begin

            // New UART byte has arrived.
            //
            // Set has priority over clear if both happen
            // during the same clock cycle.

            if (uart_rx_data_valid) begin

                uart_rx_interrupt_pending_latched <=
                    1'b1;

            end

            else if (uart_rx_interrupt_clear) begin

                uart_rx_interrupt_pending_latched <=
                    1'b0;

            end

        end

    end


    // ============================================================
    // UART RX INTERRUPT OUTPUT
    // ============================================================

    assign uart_rx_irq =
        uart_rx_interrupt_enable &&
        uart_rx_interrupt_pending_latched;


    // ============================================================
    // EXTERNAL MMIO READ DATA MUX
    // ============================================================

    assign bus_mmio_rdata =
    gpio_sel
        ? gpio_read_data
        : uart_rx_sel
            ? uart_rx_read_data
            : status_sel
                ? status_read_data
                : control_sel
                    ? {31'b0, uart_rx_interrupt_enable}
                    : 32'h00000000;


    // ============================================================
    // CPU
    // ============================================================

    riscv_core #(

        .CSR_TEST(1'b0),

        .TRAP_TEST(1'b0),

        .TIMER_TEST(1'b0),

        .MMIO_TEST(1'b0),

        .UART_TX_TEST(1'b0),

        .UART_RX_TEST(1'b0),

        .UART_RX_INTERRUPT_TEST(1'b0),

        .SOC_MODE(1'b1)

    ) core (

        .clk(clk),
        .rst(rst),

        .uart_rx(uart_rx),


        // ========================================================
        // INSTRUCTION BUS
        // ========================================================

        .imem_addr(imem_addr),
        .imem_rdata(imem_rdata),


        // ========================================================
        // EXTERNAL RAM DATA BUS
        // ========================================================

        .dmem_read(dmem_read),
        .dmem_write(dmem_write),

        .dmem_addr(dmem_addr),
        .dmem_wdata(dmem_wdata),
        .dmem_rdata(dmem_rdata),


        // ========================================================
        // EXTERNAL MMIO BUS
        // ========================================================

        .mmio_read(mmio_read),
        .mmio_write(mmio_write),

        .mmio_addr(mmio_addr),
        .mmio_wdata(mmio_wdata),
        .mmio_rdata(mmio_rdata),


        // ========================================================
        // UART RX MACHINE EXTERNAL INTERRUPT
        // ========================================================

        .uart_rx_irq(uart_rx_irq)

    );

always @(posedge clk) begin
    if (!rst) begin

        if (bus_mmio_read) begin
            $display(
                "MMIO READ: addr=%h rdata=%h gpio_sel=%b uart_rx_sel=%b status_sel=%b control_sel=%b",
                bus_mmio_addr,
                bus_mmio_rdata,
                gpio_sel,
                uart_rx_sel,
                status_sel,
                control_sel
            );
        end

        if (bus_mmio_write) begin
            $display(
                "MMIO WRITE: addr=%h wdata=%h gpio_sel=%b control_sel=%b",
                bus_mmio_addr,
                bus_mmio_wdata,
                gpio_sel,
                control_sel
            );
        end

    end
end
endmodule