`timescale 1ns/1ps

module riscv_csr (

    input  wire        clk,
    input  wire        rst,

    // =========================================================
    // CSR ACCESS
    // =========================================================

    input  wire [11:0] csr_addr,
    output reg  [31:0] csr_rdata,

    input  wire        csr_write,
    input  wire [31:0] csr_wdata,

    // =========================================================
    // TRAP
    // =========================================================

    input  wire        trap_enter,
    input  wire [31:0] trap_pc,
    input  wire [31:0] trap_cause,
    input  wire [31:0] trap_value,

    // =========================================================
    // MRET
    // =========================================================

    input  wire        mret,

    // =========================================================
    // INTERRUPT SOURCES
    // =========================================================

    // Machine timer interrupt request
    input  wire        timer_interrupt,

    // Machine external interrupt request
    // Generated by UART RX / external peripheral logic
    input  wire        uart_rx_interrupt,

    // =========================================================
    // PERFORMANCE COUNTERS
    // =========================================================

    input  wire [63:0] cycle_count,
    input  wire [63:0] instret_count,

    // =========================================================
    // TRAP TARGETS
    // =========================================================

    output wire [31:0] mtvec_value,
    output wire [31:0] mepc_value,

    // =========================================================
    // INTERRUPT PENDING OUTPUTS
    // =========================================================

    output wire        timer_interrupt_pending,
    output wire        uart_rx_interrupt_pending

);


    // =========================================================
    // MACHINE CSRs
    // =========================================================

    reg [31:0] mstatus;
    reg [31:0] mie;
    reg [31:0] mip;

    reg [31:0] mtvec;
    reg [31:0] mscratch;

    reg [31:0] mepc;
    reg [31:0] mcause;
    reg [31:0] mtval;


    // =========================================================
    // CSR ADDRESSES
    // =========================================================

    localparam [11:0] CSR_MSTATUS  = 12'h300;
    localparam [11:0] CSR_MIE      = 12'h304;
    localparam [11:0] CSR_MTVEC    = 12'h305;

    localparam [11:0] CSR_MSCRATCH = 12'h340;
    localparam [11:0] CSR_MEPC     = 12'h341;
    localparam [11:0] CSR_MCAUSE   = 12'h342;
    localparam [11:0] CSR_MTVAL    = 12'h343;
    localparam [11:0] CSR_MIP      = 12'h344;

    localparam [11:0] CSR_CYCLE    = 12'hC00;
    localparam [11:0] CSR_TIME     = 12'hC01;
    localparam [11:0] CSR_INSTRET  = 12'hC02;


    // =========================================================
    // MIP
    // =========================================================
    //
    // MIP contains the CURRENT interrupt requests.
    //
    // Bit 7  = MTIP = Machine Timer Interrupt Pending
    // Bit 11 = MEIP = Machine External Interrupt Pending
    //
    // UART RX is currently being used as the external interrupt
    // source for MEIP.
    //
    // =========================================================

    always @(*) begin

        mip = 32'b0;

        // Machine timer interrupt pending
        mip[7] = timer_interrupt;

        // Machine external interrupt pending
        // UART RX is the external interrupt source
        mip[11] = uart_rx_interrupt;

    end


    // =========================================================
    // MACHINE TIMER INTERRUPT PENDING
    // =========================================================
    //
    // Global interrupt enable:
    //     mstatus[3] = MIE
    //
    // Timer interrupt enable:
    //     mie[7] = MTIE
    //
    // Timer interrupt request:
    //     mip[7] = MTIP
    //
    // =========================================================

    assign timer_interrupt_pending =
        mstatus[3] &
        mie[7] &
        mip[7];


    // =========================================================
    // MACHINE EXTERNAL INTERRUPT PENDING
    // =========================================================
    //
    // Global interrupt enable:
    //     mstatus[3] = MIE
    //
    // External interrupt enable:
    //     mie[11] = MEIE
    //
    // External interrupt request:
    //     mip[11] = MEIP
    //
    // =========================================================

    assign uart_rx_interrupt_pending =
        mstatus[3] &
        mie[11] &
        mip[11];


    // =========================================================
    // CSR STATE
    // =========================================================

    always @(posedge clk) begin

        if (rst) begin

            mstatus  <= 32'b0;
            mie      <= 32'b0;

            mtvec    <= 32'b0;
            mscratch <= 32'b0;

            mepc     <= 32'b0;
            mcause   <= 32'b0;
            mtval    <= 32'b0;

        end

        else begin

            // =================================================
            // SOFTWARE CSR WRITE
            // =================================================

            if (csr_write) begin

                case (csr_addr)

                    CSR_MSTATUS: begin
                        mstatus <= csr_wdata;
                    end

                    CSR_MIE: begin
                        mie <= csr_wdata;
                    end

                    CSR_MTVEC: begin
                        mtvec <= csr_wdata;
                    end

                    CSR_MSCRATCH: begin
                        mscratch <= csr_wdata;
                    end

                    CSR_MEPC: begin
                        mepc <= csr_wdata;
                    end

                    CSR_MCAUSE: begin
                        mcause <= csr_wdata;
                    end

                    CSR_MTVAL: begin
                        mtval <= csr_wdata;
                    end

                    default: begin
                        // Read-only / unsupported CSR
                    end

                endcase

            end


            // =================================================
            // TRAP ENTRY
            // =================================================
            //
            // Priority over normal CSR writes for trap state.
            //
            // On trap:
            //
            //     MEPC   <- faulting PC
            //     MCAUSE <- trap cause
            //     MTVAL  <- trap value
            //     MPIE   <- MIE
            //     MIE    <- 0
            //
            // =================================================

            if (trap_enter) begin

                mepc   <= trap_pc;
                mcause <= trap_cause;
                mtval  <= trap_value;

                // Save current MIE into MPIE
                mstatus[7] <= mstatus[3];

                // Disable machine interrupts
                mstatus[3] <= 1'b0;

            end


            // =================================================
            // MRET
            // =================================================
            //
            // On MRET:
            //
            //     MIE  <- MPIE
            //     MPIE <- 1
            //
            // =================================================

            if (mret) begin

                mstatus[3] <= mstatus[7];
                mstatus[7] <= 1'b1;

            end

        end

    end


    // =========================================================
    // CSR READ
    // =========================================================

    always @(*) begin

        case (csr_addr)

            // Machine status
            CSR_MSTATUS:
                csr_rdata = mstatus;

            // Machine interrupt enable
            CSR_MIE:
                csr_rdata = mie;

            // Machine trap-vector base
            CSR_MTVEC:
                csr_rdata = mtvec;

            // Machine scratch
            CSR_MSCRATCH:
                csr_rdata = mscratch;

            // Machine exception program counter
            CSR_MEPC:
                csr_rdata = mepc;

            // Machine trap cause
            CSR_MCAUSE:
                csr_rdata = mcause;

            // Machine trap value
            CSR_MTVAL:
                csr_rdata = mtval;

            // Machine interrupt pending
            CSR_MIP:
                csr_rdata = mip;

            // Cycle counter
            CSR_CYCLE:
                csr_rdata = cycle_count[31:0];

            // Time counter
            CSR_TIME:
                csr_rdata = cycle_count[31:0];

            // Instruction-retired counter
            CSR_INSTRET:
                csr_rdata = instret_count[31:0];

            default:
                csr_rdata = 32'b0;

        endcase

    end


    // =========================================================
    // TRAP TARGETS
    // =========================================================

    assign mtvec_value = mtvec;
    assign mepc_value  = mepc;


endmodule